ironcore-dev/metal

internal/controller/machineclaim_controller.go, internal/controller/machineclaim_controller_test.go, internal/controller/suite_test.go, internal/util/utils.go
```feature user
Improve MachineClaim controller
```
=> Improve MachineClaim controller

cmd/main.go, config/rbac/role.yaml, go.mod, go.sum, internal/bmc/bmc.go, internal/controller/indexes.go, internal/controller/oob_controller.go, internal/controller/oob_controller_test.go, internal/controller/suite_test.go, internal/cru/cru.go
```feature user
Add OOB controller
```
=> Add OOB controller

config/rbac/role.yaml, internal/controller/oob_controller.go
```bugfix user
Fix RBAC permissions
```
=> Fix RBAC permissions

cmd/main.go
```feature user
Enable parallel reconciliation
```
=> Enable parallel reconciliation

internal/controller/oob_controller.go
```bugfix user
Fix infinite loop when initial credentials fail
```
=> Fix infinite loop when initial credentials fail

api/v1alpha1/oob_types.go, config/crd/bases/metal.ironcore.dev_oobs.yaml, internal/controller/oob_controller.go, internal/controller/oob_controller_test.go
```feature user
Remove Unknown state and stop creating unknown OOBs
```
=> Remove Unknown state and stop creating unknown OOBs

internal/controller/machineclaim_controller.go, internal/controller/oob_controller.go, internal/controller/suite_test.go
```feature developer
Improve debug logging
```
=> Improve debug logging

api/v1alpha1/oob_types.go, client/applyconfiguration/api/v1alpha1/oobstatus.go, client/applyconfiguration/internal/internal.go, client/openapi/zz_generated.openapi.go, config/crd/bases/metal.ironcore.dev_oobs.yaml, internal/bmc/bmc.go, internal/controller/oob_controller.go, test/macdb.yaml
```feature user
Add annotation to unknown IPs and add BMC type
```
=> Add annotation to unknown IPs and add BMC type

Makefile, internal/controller/machine_controller_test.go, internal/controller/machineclaim_controller_test.go, internal/controller/oob_controller_test.go
```bugfix developer
Improve test reliability
```
=> Improve test reliability

Makefile, api/v1alpha1/machine_types.go, config/crd/bases/metal.ironcore.dev_machines.yaml, internal/bmc/fake.go, internal/controller/indexes.go, internal/controller/machine_controller.go, internal/controller/machineclaim_controller.go, internal/controller/machineclaim_controller_test.go, internal/controller/oob_controller.go, internal/controller/oob_controller_test.go, internal/controller/suite_test.go
```feature user
Create Machines from OOBs
```
=> Create Machines from OOBs

Makefile, internal/controller/oob_controller.go
```fix user
Fix rare case of broken status
```
=> Fix rare case of broken status

api/v1alpha1/machine_types.go, api/v1alpha1/oob_types.go, client/applyconfiguration/internal/internal.go, client/openapi/zz_generated.openapi.go, cmd/main.go, config/crd/bases/metal.ironcore.dev_machineclaims.yaml, config/crd/bases/metal.ironcore.dev_machines.yaml, config/crd/bases/metal.ironcore.dev_oobs.yaml, internal/bmc/bmc.go, internal/bmc/fake.go, internal/bmc/ipmi.go, internal/bmc/redfish.go, internal/controller/oob_controller.go, internal/controller/oob_controller_test.go, internal/controller/suite_test.go
```feature user
Implement machine control
```
=> Implement machine control

cmd/main.go, internal/controller/oob_controller_test.go, test/macdb.yaml
```chore developer
Improve OOB tests
```
=> Improve OOB tests

config/rbac/role.yaml, internal/controller/machine_controller.go
=> fix missing rbac rules

internal/bmc/bmc.go, internal/bmc/fake.go, internal/bmc/ipmi.go, internal/bmc/redfish.go, internal/controller/machine_controller.go, internal/controller/oob_controller.go
```enhancement user
Validate endpoint with a BMC ping
```
=> Validate endpoint with a BMC ping

internal/controller/machine_controller.go
fix incorrect comparison of conditions and network interfaces lists in machine.status
NONE
=> fix machine to machineApply conversion

config/rbac/role.yaml, internal/controller/aggregate_controller.go, internal/controller/inventory_controller.go
=> fix manager rbac for inventories

internal/controller/machine_controller.go
fix zeroing of machine.status.state
NONE
=> fix infinite reconciliation caused by applying empty machine.status

internal/controller/machine_controller.go
check `machine.status.power` equals to "Off" before setting `machine.status.state` equals to "Available. Otherwise keep current state.
NONE
=> ensure machine power status is Off before making it available

cmd/main.go, internal/controller/cleanup_controller.go, internal/controller/machineclaim_controller.go
cleanup controller to handle "Tainted" state
NONE
=> dummy implementation of machine cleanup controller

api/v1alpha1/aggregate_types.go, api/v1alpha1/aggregation_results.go, api/v1alpha1/constraint_types.go, api/v1alpha1/constraintval_type.go, api/v1alpha1/funcs.go, api/v1alpha1/jsonpath_types.go, api/v1alpha1/size_types.go, client/openapi/zz_generated.openapi.go, internal/controller/aggregate_controller.go, internal/controller/cleanup_controller.go, internal/controller/inventory_controller.go, internal/controller/machine_controller.go, internal/controller/size_controller.go
=> licenses and const renaming

internal/controller/cleanup_controller.go, internal/controller/inventory_controller.go
power off the machine after cleanup is done to make it available again
NONE
=> power off the machine after cleanup is done

cmd/main.go, config/rbac/aggregate_editor_role.yaml, config/rbac/aggregate_viewer_role.yaml, internal/controller/aggregate_controller.go, internal/controller/inventory_controller.go, internal/controller/suite_test.go
add creation of the default aggregate object if not exists, which will be used to update inventories' status
NONE
=> update inventory status with aggregated values
